name: Deploy to GitHubPages

on: [workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Windows build
        uses: actions/download-artifact@v3
        with:
          name: build-windows-amd64
          # Windows is not in a tarball, so we extract to a separate directory.
          path: ./artifacts/windows
        
      - name: Run Conveyor     
        uses: hydraulic-software/conveyor/actions/build@v1
        with:
          command: make copied-site          
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          

