name: Deploy to GitHubPages

on:
  push:
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Download Windows build
        uses: actions/download-artifact@v3
        with:
          name: build-windows-amd64
          # Windows is not in a tarball, so we extract to a separate directory.
          path: ./artifacts/windows
        
      - name: Run Conveyor     
        uses: hydraulic-software/conveyor/actions/build@v1
        with:
          command: make copied-site          
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          

